#ifndef __N1GP_PRESET_EVENT_H__
#define __N1GP_PRESET_EVENT_H__

#include "main.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  PST_EVT_NONE = 0,
  PST_EVT_PRESET_SAVE,
  PST_EVT_PRESET_LOAD,

  PST_EVT_PRESET_TMP_SAVE,
  PST_EVT_PRESET_TMP_LOAD,

  PST_EVT_REALTIME_TMP_SAVE,
} PresetEventCmdId;

typedef enum {
  PST_EVT_TARGET_NONE = 0,
  PST_EVT_TARGET_OSC_INDEX,
  PST_EVT_TARGET_OSC_SHAPE,
  PST_EVT_TARGET_OSC_SHIFT_SHAPE,
  PST_EVT_TARGET_OSC_LFO_RATE,
  PST_EVT_TARGET_OSC_LFO_DEPTH,
  PST_EVT_TARGET_OSC_CUSTOM_VALUES,

  PST_EVT_TARGET_FILTER_INDEX,
  PST_EVT_TARGET_FILTER_CUTOFF,
  PST_EVT_TARGET_FILTER_PEAK,
  PST_EVT_TARGET_FILTER_LFO_RATE,
  PST_EVT_TARGET_FILTER_LFO_DEPTH,

  PST_EVT_TARGET_AMPEG_INDEX,
  PST_EVT_TARGET_AMPEG_ATTACK,
  PST_EVT_TARGET_AMPEG_RELEASE,
  PST_EVT_TARGET_AMPEG_LFO_RATE,
  PST_EVT_TARGET_AMPEG_LFO_DEPTH,

  PST_EVT_TARGET_MODFX_INDEX,
  PST_EVT_TARGET_MODFX_TIME,
  PST_EVT_TARGET_MODFX_DEPTH,

  PST_EVT_TARGET_DELFX_INDEX,
  PST_EVT_TARGET_DELFX_TIME,
  PST_EVT_TARGET_DELFX_DEPTH,
  PST_EVT_TARGET_DELFX_MIX,

  PST_EVT_TARGET_REVFX_INDEX,
  PST_EVT_TARGET_REVFX_TIME,
  PST_EVT_TARGET_REVFX_DEPTH,
  PST_EVT_TARGET_REVFX_MIX,

  PST_EVT_TARGET_ARP_INDEX,
  PST_EVT_TARGET_ARP_INTERVALS,
  PST_EVT_TARGET_ARP_LENGTH,
  PST_EVT_TARGET_ARP_STATE,
  PST_EVT_TARGET_ARP_TEMPO,

  PST_EVT_TARGET_LFO_INDEX,
  PST_EVT_TARGET_LFO_RATE,
  PST_EVT_TARGET_LFO_DEPTH,
  PST_EVT_TARGET_LFO_BPM_SYNC,

  PST_EVT_TARGET_SCALE_INDEX,

  PST_EVT_TARGET_TRANSPOSE_OFFSET,

  PST_EVT_TARGET_STUTTER_INDEX,

  PST_EVT_TARGET_SLIDE_VALUE,
  PST_EVT_TARGET_SLIDE_TYPE,

  PST_EVT_TARGET_RAND_PITCH,
} PresetEventTargetId;

typedef struct {
  uint8_t command_id;
  uint8_t target_id;
  int16_t value;
} PresetEvent;

void preset_event_add(PresetEvent preset_event);
PresetEvent preset_event_get();
uint8_t preset_event_is_empty();

static inline void preset_event_create(uint8_t command_id, uint8_t target_id, int16_t value) {
  PresetEvent event = {command_id, target_id, value}; 
  preset_event_add(event);
}

#ifdef __cplusplus
}
#endif

#endif /* __N1GP_PRESET_EVENT_H__ */
