// Generated by svd_parser.rb. Dont't edit please.
#ifndef IGB_STM32_DEVICE_MCU_STM32F072XB_H
#define IGB_STM32_DEVICE_MCU_STM32F072XB_H

#include <igb_stm32/base/svd/stm32f072x.hpp>

#endif /* IGB_STM32_DEVICE_MCU_STM32F072XB_H */
