// Generated by svd_parser.rb. Dont't edit please.
#ifndef IGB_STM32_BASE_MCU_STM32F072XB_H
#define IGB_STM32_BASE_MCU_STM32F072XB_H

#include <igb_stm32/base/mcu/device/stm32f072xb.hpp>

#endif /* IGB_STM32_BASE_MCU_STM32F072XB_H */
